import 'package:app_clone_mercado_livre/models/product_model.dart';

List<Product> productDatabase = [
  Product(
    id: 1,
    name: "Apple Iphone 11 Pro (128gb) - Preto",
    price: 599.99,
    image: "assets/images/iphone.png",
    rating: "",
  ),
  Product(
    id: 2,
    name: "Apple Iphone 11 Pro (128gb) - Preto",
    price: 599.99,
    image: "assets/images/iphone.png",
    rating: "",
  ),
  Product(
    id: 3,
    name: "Apple Iphone 11 Pro (128gb) - Preto",
    price: 599.99,
    image: "assets/images/iphone.png",
    rating: "",
  ),
  Product(
    id: 4,
    name: "Apple Iphone 11 Pro (128gb) - Preto",
    price: 599.99,
    image: "assets/images/iphone.png",
    rating: "",
  ),
  Product(
    id: 5,
    name: "Apple Iphone 11 Pro (128gb) - Preto",
    price: 599.99,
    image: "assets/images/iphone.png",
    rating: "",
  ),
  Product(
    id: 6,
    name: "Apple Iphone 11 Pro (128gb) - Preto",
    price: 599.99,
    image: "assets/images/iphone.png",
    rating: "",
  ),
  Product(
    id: 7,
    name: "Apple Iphone 11 Pro (128gb) - Preto",
    price: 599.99,
    image: "assets/images/iphone.png",
    rating: "",
  ),
  Product(
    id: 8,
    name: "Apple Iphone 11 Pro (128gb) - Preto",
    price: 599.99,
    image: "assets/images/iphone.png",
    rating: "",
  ),
  Product(
    id: 9,
    name: "Apple Iphone 11 Pro (128gb) - Preto",
    price: 599.99,
    image: "assets/images/iphone.png",
    rating: "",
  ),
  Product(
    id: 10,
    name: "Apple Iphone 11 Pro (128gb) - Preto",
    price: 599.99,
    image: "assets/images/iphone.png",
    rating: "",
  ),
  Product(
    id: 11,
    name: "Apple Iphone 11 Pro (128gb) - Preto",
    price: 599.99,
    image: "assets/images/iphone.png",
    rating: "",
  ),
  Product(
    id: 12,
    name: "Apple Iphone 11 Pro (128gb) - Preto",
    price: 599.99,
    image: "assets/images/iphone.png",
    rating: "",
  ),
  Product(
    id: 13,
    name: "Apple Iphone 11 Pro (128gb) - Preto",
    price: 599.99,
    image: "assets/images/iphone.png",
    rating: "",
  ),
  Product(
    id: 14,
    name: "Apple Iphone 11 Pro (128gb) - Preto",
    price: 599.99,
    image: "assets/images/iphone.png",
    rating: "",
  ),
  Product(
    id: 15,
    name: "Apple Iphone 11 Pro (128gb) - Preto",
    price: 599.99,
    image: "assets/images/iphone.png",
    rating: "",
  ),
];
